"""
SignalIQ - Supervisor Agent

Combines outputs from:
- News Agent
- Fundamental Agent
- Technical Agent
- Risk Agent

Produces one final investment recommendation for a company.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger


class SupervisorAgent:
    """
    Combine all agent reports into one final investment report.

    The Supervisor Agent does not recollect data. It reads the JSON
    reports already generated by the specialized agents.
    """

    def __init__(
        self,
        news_dir: str | Path = "Data/analysis/news",
        fundamental_dir: str | Path = "Data/analysis/fundamental",
        technical_dir: str | Path = "Data/analysis/technical",
        risk_dir: str | Path = "Data/analysis/risk",
        output_dir: str | Path = "Data/analysis/supervisor",
    ) -> None:
        self.news_dir = Path(news_dir)
        self.fundamental_dir = Path(fundamental_dir)
        self.technical_dir = Path(technical_dir)
        self.risk_dir = Path(risk_dir)
        self.output_dir = Path(output_dir)

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

    # ==========================================================
    # Public API
    # ==========================================================

    def run(
        self,
        symbol: str,
        save: bool = True,
    ) -> dict[str, Any]:
        """
        Generate the final analysis for one company.

        Args:
            symbol:
                Saudi Exchange company symbol.

            save:
                Save the final report as JSON.

        Returns:
            Combined supervisor report.
        """

        symbol = self._clean_symbol(symbol)

        logger.info(
            "Starting supervisor analysis for {}.",
            symbol,
        )

        news_report = self._load_report(
            directory=self.news_dir,
            symbol=symbol,
            agent_name="news",
        )

        fundamental_report = self._load_report(
            directory=self.fundamental_dir,
            symbol=symbol,
            agent_name="fundamental",
        )

        technical_report = self._load_report(
            directory=self.technical_dir,
            symbol=symbol,
            agent_name="technical",
        )

        risk_report = self._load_report(
            directory=self.risk_dir,
            symbol=symbol,
            agent_name="risk",
        )

        news_score = self._extract_score(
            report=news_report,
            default=50.0,
        )

        fundamental_score = self._extract_score(
            report=fundamental_report,
            default=50.0,
        )

        technical_score = self._extract_score(
            report=technical_report,
            default=50.0,
        )

        risk_score = self._extract_risk_score(
            report=risk_report,
        )

        final_score = self._calculate_final_score(
            news_score=news_score,
            fundamental_score=fundamental_score,
            technical_score=technical_score,
            risk_score=risk_score,
        )

        recommendation = self._get_recommendation(
            final_score
        )

        confidence = self._calculate_confidence(
            reports=[
                news_report,
                fundamental_report,
                technical_report,
                risk_report,
            ],
        )

        strengths = self._collect_strengths(
            news_report=news_report,
            fundamental_report=fundamental_report,
            technical_report=technical_report,
        )

        risks = self._collect_risks(
            news_report=news_report,
            fundamental_report=fundamental_report,
            technical_report=technical_report,
            risk_report=risk_report,
        )

        company_name = self._extract_company_name(
            news_report=news_report,
            fundamental_report=fundamental_report,
            symbol=symbol,
        )

        report = {
            "symbol": symbol,
            "company_name": company_name,
            "generated_at": datetime.now().isoformat(),
            "final_score": round(final_score, 2),
            "recommendation": recommendation,
            "confidence": round(confidence, 4),
            "component_scores": {
                "fundamental": round(
                    fundamental_score,
                    2,
                ),
                "technical": round(
                    technical_score,
                    2,
                ),
                "news": round(
                    news_score,
                    2,
                ),
                "risk": round(
                    risk_score,
                    2,
                ),
            },
            "weights": {
                "fundamental": 0.35,
                "technical": 0.30,
                "news": 0.20,
                "risk": 0.15,
            },
            "strengths": strengths,
            "risks": risks,
            "summary": self._build_summary(
                company_name=company_name,
                final_score=final_score,
                recommendation=recommendation,
                confidence=confidence,
                strengths=strengths,
                risks=risks,
            ),
            "agent_status": {
                "news": (
                    "available"
                    if news_report
                    else "missing"
                ),
                "fundamental": (
                    "available"
                    if fundamental_report
                    else "missing"
                ),
                "technical": (
                    "available"
                    if technical_report
                    else "missing"
                ),
                "risk": (
                    "available"
                    if risk_report
                    else "missing"
                ),
            },
        }

        if save:
            self._save_report(
                symbol=symbol,
                report=report,
            )

        logger.success(
            "Supervisor completed {}: score={}, "
            "recommendation={}.",
            symbol,
            report["final_score"],
            report["recommendation"],
        )

        return report

    # ==========================================================
    # Report Loading
    # ==========================================================

    def _load_report(
        self,
        directory: Path,
        symbol: str,
        agent_name: str,
    ) -> dict[str, Any] | None:
        """
        Load one specialized-agent report.

        Missing reports do not stop the Supervisor Agent.
        """

        report_file = directory / f"{symbol}.json"

        if not report_file.exists():
            logger.warning(
                "{} report not found for {}: {}",
                agent_name.capitalize(),
                symbol,
                report_file,
            )

            return None

        try:
            with report_file.open(
                "r",
                encoding="utf-8",
            ) as file:
                report = json.load(file)

        except json.JSONDecodeError as exc:
            logger.error(
                "Invalid {} report JSON for {}: {}",
                agent_name,
                symbol,
                exc,
            )

            return None

        except OSError as exc:
            logger.error(
                "Could not read {} report for {}: {}",
                agent_name,
                symbol,
                exc,
            )

            return None

        if not isinstance(report, dict):
            logger.warning(
                "{} report for {} is not a JSON object.",
                agent_name.capitalize(),
                symbol,
            )

            return None

        return report

    # ==========================================================
    # Score Extraction
    # ==========================================================

    def _extract_score(
        self,
        report: dict[str, Any] | None,
        default: float = 50.0,
    ) -> float:
        """
        Extract a score from different report structures.

        Supported formats:

            {"score": 75}

            {"score": {"score": 75}}

            {"fundamental_score": 75}

            {"technical_score": 75}
        """

        if not report:
            return default

        possible_values = (
            report.get("final_score"),
            report.get("overall_score"),
            report.get("fundamental_score"),
            report.get("technical_score"),
            report.get("news_score"),
            report.get("score"),
        )

        for value in possible_values:
            if isinstance(value, dict):
                value = value.get("score")

            numeric_value = self._to_float(value)

            if numeric_value is not None:
                return self._normalize_score(
                    numeric_value
                )

        return default

    def _extract_risk_score(
        self,
        report: dict[str, Any] | None,
    ) -> float:
        """
        Convert risk information into a 0-100 safety score.

        A high risk score means lower investment risk.
        """

        if not report:
            return 50.0

        direct_score = (
            report.get("risk_score")
            or report.get("score")
        )

        if isinstance(direct_score, dict):
            direct_score = direct_score.get("score")

        numeric_score = self._to_float(
            direct_score
        )

        if numeric_score is not None:
            return self._normalize_score(
                numeric_score
            )

        risk_level = str(
            report.get("risk_level", "")
        ).strip().casefold()

        risk_level_scores = {
            "very low": 90.0,
            "low": 80.0,
            "medium": 60.0,
            "moderate": 60.0,
            "high": 35.0,
            "very high": 20.0,
            "critical": 10.0,
        }

        if risk_level in risk_level_scores:
            return risk_level_scores[risk_level]

        volatility = self._to_float(
            report.get("volatility")
        )

        max_drawdown = self._to_float(
            report.get("max_drawdown")
        )

        risk_penalty = 0.0

        if volatility is not None:
            # Supports either 0.25 or 25.
            if abs(volatility) <= 1:
                volatility *= 100

            risk_penalty += min(
                abs(volatility),
                50,
            )

        if max_drawdown is not None:
            if abs(max_drawdown) <= 1:
                max_drawdown *= 100

            risk_penalty += min(
                abs(max_drawdown),
                50,
            )

        if volatility is not None or max_drawdown is not None:
            return max(
                0.0,
                min(
                    100.0,
                    100.0 - risk_penalty,
                ),
            )

        return 50.0

    # ==========================================================
    # Final Decision
    # ==========================================================

    @staticmethod
    def _calculate_final_score(
        news_score: float,
        fundamental_score: float,
        technical_score: float,
        risk_score: float,
    ) -> float:
        """
        Calculate the weighted final investment score.
        """

        final_score = (
            fundamental_score * 0.35
            + technical_score * 0.30
            + news_score * 0.20
            + risk_score * 0.15
        )

        return max(
            0.0,
            min(
                100.0,
                final_score,
            ),
        )

    @staticmethod
    def _get_recommendation(
        final_score: float,
    ) -> str:
        """
        Convert the final score into a recommendation.
        """

        if final_score >= 80:
            return "Strong Buy"

        if final_score >= 65:
            return "Buy"

        if final_score >= 45:
            return "Hold"

        if final_score >= 30:
            return "Sell"

        return "Strong Sell"

    @staticmethod
    def _calculate_confidence(
        reports: list[dict[str, Any] | None],
    ) -> float:
        """
        Estimate confidence from available agent reports.
        """

        available_reports = sum(
            report is not None
            for report in reports
        )

        return available_reports / len(reports)

    # ==========================================================
    # Strengths and Risks
    # ==========================================================

    def _collect_strengths(
        self,
        news_report: dict[str, Any] | None,
        fundamental_report: dict[str, Any] | None,
        technical_report: dict[str, Any] | None,
    ) -> list[str]:
        strengths: list[str] = []

        for report in (
            fundamental_report,
            technical_report,
            news_report,
        ):
            if not report:
                continue

            strengths.extend(
                self._extract_string_list(
                    report.get("strengths")
                )
            )

            score_section = report.get("score")

            if isinstance(score_section, dict):
                strengths.extend(
                    self._extract_string_list(
                        score_section.get("strengths")
                    )
                )

            summary_section = report.get("summary")

            if isinstance(summary_section, dict):
                strengths.extend(
                    self._extract_string_list(
                        summary_section.get(
                            "opportunities"
                        )
                    )
                )

        return self._unique_strings(
            strengths
        )[:10]

    def _collect_risks(
        self,
        news_report: dict[str, Any] | None,
        fundamental_report: dict[str, Any] | None,
        technical_report: dict[str, Any] | None,
        risk_report: dict[str, Any] | None,
    ) -> list[str]:
        risks: list[str] = []

        for report in (
            fundamental_report,
            technical_report,
            news_report,
            risk_report,
        ):
            if not report:
                continue

            risks.extend(
                self._extract_string_list(
                    report.get("risks")
                )
            )

            score_section = report.get("score")

            if isinstance(score_section, dict):
                risks.extend(
                    self._extract_string_list(
                        score_section.get("risks")
                    )
                )

            summary_section = report.get("summary")

            if isinstance(summary_section, dict):
                risks.extend(
                    self._extract_string_list(
                        summary_section.get("risks")
                    )
                )

        return self._unique_strings(
            risks
        )[:10]

    # ==========================================================
    # Summary
    # ==========================================================

    @staticmethod
    def _build_summary(
        company_name: str,
        final_score: float,
        recommendation: str,
        confidence: float,
        strengths: list[str],
        risks: list[str],
    ) -> str:
        confidence_label = (
            "high"
            if confidence >= 0.75
            else "moderate"
            if confidence >= 0.50
            else "low"
        )

        summary = (
            f"{company_name} received a final investment score "
            f"of {final_score:.1f}/100, resulting in a "
            f"{recommendation} recommendation. "
            f"The recommendation has {confidence_label} confidence "
            f"based on the available agent reports."
        )

        if strengths:
            summary += (
                f" Main strength: {strengths[0]}."
            )

        if risks:
            summary += (
                f" Main risk: {risks[0]}."
            )

        return summary

    # ==========================================================
    # Saving
    # ==========================================================

    def _save_report(
        self,
        symbol: str,
        report: dict[str, Any],
    ) -> Path:
        output_file = (
            self.output_dir / f"{symbol}.json"
        )

        temporary_file = (
            output_file.with_suffix(".json.tmp")
        )

        with temporary_file.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                report,
                file,
                indent=4,
                ensure_ascii=False,
            )

        temporary_file.replace(output_file)

        logger.info(
            "Supervisor report saved to {}.",
            output_file,
        )

        return output_file

    # ==========================================================
    # Helpers
    # ==========================================================

    @staticmethod
    def _extract_company_name(
        news_report: dict[str, Any] | None,
        fundamental_report: dict[str, Any] | None,
        symbol: str,
    ) -> str:
        for report in (
            news_report,
            fundamental_report,
        ):
            if not report:
                continue

            for key in (
                "company_name",
                "name",
                "companyName",
            ):
                value = report.get(key)

                if value:
                    return str(value).strip()

        return symbol

    @staticmethod
    def _normalize_score(
        score: float,
    ) -> float:
        """
        Normalize scores to a 0-100 range.

        Supports:
        - 0 to 100
        - 0 to 1
        - -1 to 1
        """

        if -1.0 <= score < 0:
            return (score + 1.0) * 50.0

        if 0.0 <= score <= 1.0:
            return score * 100.0

        return max(
            0.0,
            min(
                100.0,
                score,
            ),
        )

    @staticmethod
    def _to_float(
        value: Any,
    ) -> float | None:
        if value is None:
            return None

        if isinstance(value, bool):
            return None

        try:
            return float(value)

        except (TypeError, ValueError):
            return None

    @staticmethod
    def _extract_string_list(
        value: Any,
    ) -> list[str]:
        if value is None:
            return []

        if isinstance(value, str):
            cleaned = value.strip()

            return [cleaned] if cleaned else []

        if isinstance(value, list):
            return [
                str(item).strip()
                for item in value
                if str(item).strip()
            ]

        return []

    @staticmethod
    def _unique_strings(
        values: list[str],
    ) -> list[str]:
        unique: list[str] = []
        seen: set[str] = set()

        for value in values:
            cleaned = " ".join(
                str(value).strip().split()
            )

            if not cleaned:
                continue

            normalized = cleaned.casefold()

            if normalized in seen:
                continue

            seen.add(normalized)
            unique.append(cleaned)

        return unique

    @staticmethod
    def _clean_symbol(
        symbol: str,
    ) -> str:
        cleaned = str(symbol).strip()

        if cleaned.endswith(".0"):
            cleaned = cleaned[:-2]

        if not cleaned:
            raise ValueError(
                "Symbol cannot be empty."
            )

        return cleaned